FROM python:3.8

WORKDIR /usr/src/app

COPY ./toy-backend .

RUN apt-get update -y && \
    apt-get install libglib2.0-0 -y && \
    apt-get install libgl1-mesa-glx -y && \
    pip install tensorflow==2.7.0 --no-cache-dir && \
    pip install -r requirements.txt

ENV PYTHONPATH="${PYTHONPATH}:/"

ENV HOME=.

ENV ENV=test

ENV FLASK_ENV=deployment

EXPOSE 5000

CMD ["python3", "toy_backend/app.py"]