FROM node:alpine AS build-step

WORKDIR /build

# ENV PATH /build/node_modules/.bin:$PATH

COPY ./toy-frontend/package.json ./
COPY ./toy-frontend/package-lock.json ./

RUN npm install --force

COPY ./toy-frontend .
RUN npm run build

FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build-step /build/build /frontend/build