FROM node:alpine

WORKDIR /build

ENV PATH /build/node_modules/.bin:$PATH

COPY ./toy-frontend/package.json ./
COPY ./toy-frontend/package-lock.json ./

RUN npm install --force

COPY ./toy-frontend .

RUN npm install -g serve

RUN npm run build

ENTRYPOINT ["serve", "-s", "build"]